active: true
control_frequency: 70
lookahead_distance: 0.3
robot_L: 0.3

# linear
xy_tolerance: 0.02
linear_max_vel: 0.5
linear_acceleration: 0.2
linear_kp: 0.8
linear_brake_distance: 0.15
linear_min_brake_distance: 0.25
linear_brake_distance_ratio: 0.3

# angular
theta_tolerance: 0.03
angular_max_vel: 3.0
# angular_acceleration: 0.15
angular_kp: 1.5
# angular_brake_distance: 0.15
# angular_min_brake_distance: 0.15
# angular_brake_distance_ratio: 0.15
